import fs from 'node:fs/promises';
import path from 'node:path';

const SITE = 'https://niletropicaluganda.com';
const SUPABASE_URL = (process.env.SUPABASE_URL || '').replace(/\/$/, '');
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const OUT = path.resolve('build/seo-site');
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) throw new Error('SUPABASE_URL and SUPABASE_ANON_KEY are required.');
const headers = { apikey: SUPABASE_ANON_KEY };
const esc = (v='') => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const json = v => JSON.stringify(v).replaceAll('<','\\u003c');
async function api(table, params) {
  const u = new URL(SUPABASE_URL + '/rest/v1/' + table);
  Object.entries(params).forEach(([k,v]) => u.searchParams.set(k,v));
  const r = await fetch(u, {headers});
  if (!r.ok) throw new Error('Supabase REST ' + table + ' failed: ' + r.status + ' ' + await r.text());
  return r.json();
}
const products = await api('products', {select:'id,slug,name,short_description,full_description,benefits,how_to_use,ingredients,warnings,brand,seo_title,seo_description,category_id,updated_at',is_active:'eq.true',deleted_at:'is.null',order:'name.asc'});
const variants = await api('product_variants', {select:'id,product_id,sku,name,price,compare_at_price,stock_quantity,barcode,updated_at',is_active:'eq.true',order:'name.asc'});
const images = await api('product_images', {select:'id,product_id,variant_id,storage_path,alt_text,is_main,sort_order',order:'sort_order.asc'});
const categories = await api('categories', {select:'id,name,slug,description,sort_order,updated_at',is_active:'eq.true',deleted_at:'is.null',order:'sort_order.asc'});
const byProduct = new Map(), imageByProduct = new Map(), categoryById = new Map(categories.map(c=>[c.id,c]));
for (const v of variants) { if (!byProduct.has(v.product_id)) byProduct.set(v.product_id,[]); byProduct.get(v.product_id).push(v); }
for (const i of images) { if (!imageByProduct.has(i.product_id)) imageByProduct.set(i.product_id,[]); imageByProduct.get(i.product_id).push(i); }
const imageUrl = p => p ? SUPABASE_URL + '/storage/v1/object/public/product-images/' + p.split('/').map(encodeURIComponent).join('/') : '';
const desc = p => String(p.seo_description || p.short_description || p.full_description || (p.name + ' from Nile Tropical Industries, Uganda.')).replace(/\\s+/g,' ').trim().slice(0,300);
const avail = v => Number(v.stock_quantity || 0) > 0 ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock';
function productHtml(p) {
  const vs=byProduct.get(p.id)||[], ims=(imageByProduct.get(p.id)||[]).slice().sort((a,b)=>Number(b.is_main)-Number(a.is_main)||a.sort_order-b.sort_order), cat=categoryById.get(p.category_id);
  const url=SITE+'/products/'+encodeURIComponent(p.slug)+'/', title=p.seo_title||p.name+' | Nile Tropical Uganda', d=desc(p), main=ims[0] ? imageUrl(ims[0].storage_path) : '';
  const variantsLd=vs.map(v=>({'@type':'Product','@id':url+'#variant-'+v.id,name:[p.name,v.name].filter(Boolean).join(' – '),sku:v.sku,...(v.barcode?{gtin:v.barcode}:{}),brand:{'@type':'Brand',name:p.brand||'Nile Tropical'},image:ims.filter(i=>i.storage_path).map(i=>imageUrl(i.storage_path)),description:d,offers:{'@type':'Offer','@id':url+'#offer-'+v.id,url,price:Number(v.price),priceCurrency:'UGX',availability:avail(v),itemCondition:'https://schema.org/NewCondition'},isVariantOf:{'@id':url+'#product-group'}}));
  const graph=[{'@type':'ProductGroup','@id':url+'#product-group',name:p.name,description:d,productGroupID:p.id,url,brand:{'@type':'Brand',name:p.brand||'Nile Tropical'},hasVariant:variantsLd.map(x=>({'@id':x['@id']}))},...variantsLd,{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE+'/'},...(cat?[{'@type':'ListItem',position:2,name:cat.name,item:SITE+'/categories/'+encodeURIComponent(cat.slug)+'/'}]:[]),{'@type':'ListItem',position:cat?3:2,name:p.name,item:url}]}];
  const sections=[['About this product',p.full_description],['Benefits',p.benefits],['How to use',p.how_to_use],['Ingredients',p.ingredients],['Warnings',p.warnings]].filter(x=>x[1]&&String(x[1]).trim());
  const cards=vs.map(v=>'<div class="offer"><strong class="price">UGX '+Number(v.price).toLocaleString('en-UG')+'</strong><div class="stock">'+(Number(v.stock_quantity||0)>0?'In stock':'Currently out of stock')+' · '+esc(v.name||v.sku)+'</div><a class="cta" href="'+SITE+'/app/#/product/'+encodeURIComponent(p.slug)+'">Buy from Nile Tropical</a></div>').join('');
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><meta name="description" content="'+esc(d)+'"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="'+esc(url)+'"><meta property="og:type" content="product"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(d)+'"><meta property="og:url" content="'+esc(url)+'">'+(main?'<meta property="og:image" content="'+esc(main)+'">':'')+'<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'+esc(title)+'"><meta name="twitter:description" content="'+esc(d)+'">'+(main?'<meta name="twitter:image" content="'+esc(main)+'">':'')+'<script type="application/ld+json">'+json({'@context':'https://schema.org','@graph':graph})+'</script><style>'+styles()+'</style></head><body><header><div class="wrap nav"><a class="brand" href="'+SITE+'/">Nile Tropical Industries (U) Ltd</a><a class="shop" href="'+SITE+'/app/">Shop</a></div></header><main class="wrap"><nav class="crumbs" aria-label="Breadcrumb"><a href="'+SITE+'/">Home</a> › '+(cat?'<a href="'+SITE+'/categories/'+encodeURIComponent(cat.slug)+'/">'+esc(cat.name)+'</a> › ':'')+esc(p.name)+'</nav><section class="hero"><div>'+(main?'<img src="'+esc(main)+'" alt="'+esc(ims[0].alt_text||p.name)+'" width="900" height="900" fetchpriority="high">':'')+'</div><div><div class="kicker">'+esc(cat?cat.name:'Nile Tropical product')+'</div><h1>'+esc(p.name)+'</h1><p class="desc">'+esc(d)+'</p>'+cards+'</div></section><section class="content">'+sections.map(x=>'<h2>'+esc(x[0])+'</h2><p>'+esc(x[1])+'</p>').join('')+(vs.length>1?'<h2>Available variants</h2><div class="variants">'+vs.map(v=>'<div class="variant"><b>'+esc(v.name)+'</b><span>SKU '+esc(v.sku)+'</span><br><strong>UGX '+Number(v.price).toLocaleString('en-UG')+'</strong></div>').join('')+'</div>':'')+'</section></main><footer><div class="wrap">© Nile Tropical Industries (U) Ltd · Nebbi, West Nile, Uganda · <a href="'+SITE+'/privacy.html">Privacy</a> · <a href="'+SITE+'/terms.html">Terms</a></div></footer></body></html>';
}
function styles(){return 'body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#17212b;line-height:1.7}a{color:inherit}.wrap{width:min(1100px,calc(100% - 32px));margin:auto}header{border-bottom:1px solid #dfe5e9;padding:16px 0;position:sticky;top:0;background:#fff;z-index:5}.nav{display:flex;justify-content:space-between;align-items:center}.brand{font-weight:800;color:#003d70;text-decoration:none}.shop,.cta{background:#005090;color:#fff;padding:11px 17px;border-radius:10px;text-decoration:none;font-weight:800}.crumbs{font-size:13px;color:#66717c;padding:22px 0}.hero{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:44px;align-items:center;padding:30px 0 70px}.hero img{width:100%;max-height:560px;object-fit:contain;border-radius:20px;background:#f5f8f9}.kicker{color:#08783d;font-weight:800;text-transform:uppercase;letter-spacing:.1em;font-size:12px}h1{font-size:clamp(34px,5vw,58px);line-height:1.05;color:#003d70;margin:10px 0 18px}.desc{font-size:18px;color:#66717c}.offer{border:1px solid #dfe5e9;border-radius:16px;padding:18px;margin:16px 0;background:#faf9f4}.price{font-size:28px;color:#003d70}.stock{font-size:13px;color:#08783d;font-weight:700}.content{max-width:780px;padding:0 0 70px}.content h2{color:#003d70;margin-top:35px}.variants{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.variant{border:1px solid #dfe5e9;border-radius:14px;padding:16px}.variant b{display:block;color:#003d70}footer{border-top:1px solid #dfe5e9;padding:28px 0;color:#66717c;font-size:13px}@media(max-width:760px){.hero{grid-template-columns:1fr}.wrap{width:calc(100% - 24px)}}';}
async function categoryHtml(c){const ps=products.filter(p=>p.category_id===c.id),url=SITE+'/categories/'+encodeURIComponent(c.slug)+'/',d=String(c.description||('Explore '+c.name+' products from Nile Tropical Industries, Uganda.')).replace(/\\s+/g,' ').trim().slice(0,300);const items=ps.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:SITE+'/products/'+encodeURIComponent(p.slug)+'/'}));return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(c.name)+' | Nile Tropical Uganda</title><meta name="description" content="'+esc(d)+'"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="'+esc(url)+'"><meta property="og:title" content="'+esc(c.name)+' | Nile Tropical Uganda"><meta property="og:description" content="'+esc(d)+'"><meta property="og:url" content="'+esc(url)+'"><script type="application/ld+json">'+json({'@context':'https://schema.org','@type':'CollectionPage','name':c.name,'description':d,'url':url,'mainEntity':{'@type':'ItemList','itemListElement':items}})+'</script><style>body{font-family:Arial,sans-serif;color:#17212b;line-height:1.7;margin:0}.wrap{width:min(1100px,calc(100% - 32px));margin:auto}header{padding:18px 0;border-bottom:1px solid #dfe5e9}h1{color:#003d70;font-size:clamp(34px,5vw,56px)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;padding:30px 0 70px}.card{border:1px solid #dfe5e9;border-radius:16px;padding:20px;text-decoration:none;color:inherit}.card h2{color:#003d70;font-size:19px}.price{font-weight:800;color:#08783d}</style></head><body><header><div class="wrap"><a href="'+SITE+'/">Nile Tropical Industries (U) Ltd</a></div></header><main class="wrap"><p><a href="'+SITE+'/">Home</a> › '+esc(c.name)+'</p><h1>'+esc(c.name)+'</h1><p>'+esc(d)+'</p><section class="grid">'+ps.map(p=>{const v=(byProduct.get(p.id)||[])[0],im=(imageByProduct.get(p.id)||[]).find(x=>x.is_main)||(imageByProduct.get(p.id)||[])[0];return '<a class="card" href="'+SITE+'/products/'+encodeURIComponent(p.slug)+'/">'+(im?.storage_path?'<img src="'+esc(imageUrl(im.storage_path))+'" alt="'+esc(im.alt_text||p.name)+'" width="500" height="500" loading="lazy" style="width:100%;height:220px;object-fit:contain">':'')+'<h2>'+esc(p.name)+'</h2><p>'+esc(desc(p))+'</p>'+(v?'<div class="price">From UGX '+Number(v.price).toLocaleString('en-UG')+'</div>':'')+'</a>'}).join('')+'</section></main></body></html>';}
await fs.rm(OUT,{recursive:true,force:true}); await fs.mkdir(OUT,{recursive:true});
for(const p of products){const d=path.join(OUT,'products',p.slug);await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'index.html'),productHtml(p));}
for(const c of categories){const d=path.join(OUT,'categories',c.slug);await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'index.html'),await categoryHtml(c));}
const urls=[{loc:SITE+'/'},{loc:SITE+'/privacy.html'},{loc:SITE+'/terms.html'},...categories.map(c=>({loc:SITE+'/categories/'+encodeURIComponent(c.slug)+'/',lastmod:c.updated_at})),...products.map(p=>({loc:SITE+'/products/'+encodeURIComponent(p.slug)+'/',lastmod:p.updated_at}))];
const xmlEsc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+xmlEsc(u.loc)+'</loc>'+(u.lastmod?'<lastmod>'+new Date(u.lastmod).toISOString().slice(0,10)+'</lastmod>':'')+'</url>').join('\n')+'\n</urlset>\n';
await fs.writeFile(path.join(OUT,'sitemap.xml'),sitemap); await fs.writeFile(path.join(OUT,'robots.txt'),'User-agent: *\nAllow: /\n\nSitemap: '+SITE+'/sitemap.xml\n');
await fs.writeFile(path.join(OUT,'SEO_BUILD_MANIFEST.json'),JSON.stringify({generatedAt:new Date().toISOString(),productCount:products.length,categoryCount:categories.length,source:'Supabase authoritative public catalogue',site:SITE},null,2));
console.log('Generated SEO pages for '+products.length+' products and '+categories.length+' categories.');